### ISSUE TITLE
 It should be possible to relate Tasks and Events

### ISSUE THREAD

**Issue by rsto** [CalConnect/PUBLIC_DRAFTS#3]
From: Adrian Apthorp
To: draft-jenkins-jscalendar@ietf.org
Subject: Mail regarding draft-jenkins-jscalendar
Date: Sunday, August 20, 2017 12:21

RFC5545 allows relationships between calendar objects and therefore constraining to objects of the same type seems restrictive. It should be possible to relate Tasks and Events together.

**Comment by rsto** [comment]
Addendum: I'm all for this but it needs to stay in sync with any changes to this requirement

        "3.1.2. uid: [...] all JSCalendar objects share the same id space."

**Comment by dmfs** [comment]
one option: instead of making it a requirement that all "related" objects are of the same type, we could make the `uid` an opaque URI like `jsevent:<uid>` or `jstask:<uid>` and allow linking any calendar object.

Client can easily filter any objects it doesn't support.

**Comment by rsto** [comment]
I'm not fond of the idea to use URIs to encode the event type in the `relatedTo` string, it requires clients to detangle a string where an additional property in a JSON `Relation` object seems more in line with the rest of JSCalendar. But I don't think the type information belongs in the relation.

I plan to just remove the `of the same object type` restriction from `relatedTo` (just as RFC5545 does). Clients that are only interested in JSEvent or JSTask should negotiate with the server which object types they request.

Please let me know if you have objections to that.

P.S.: I read dmfs' comment as an attempt to prevent what client implementations have to deal with regards to CalDAV multi-type collections. I wish we would have been able to completely decouple the calendar object types in contrast to iCalendar, but I think it's too late for that (due to the addition of JSGroup and JSTask as well as direct mapping iCalendar UID to JSCalendar `uid`).

**Comment by dmfs** [comment]
I didn't want to propose to just add a `jsevent` prefix to the `relatedTo` String. I proposed to generally encode UIDs into URIs like in this example:

```json
{
  "@type": "event",
  "uid": "jsevent:2a358cee-6489-4f14-a57f-c104db4dc357",
  "start": "2016-09-28T16:00:00",
  "relatedTo": {
     "jstask:973c285f-79ef-44b5-9266-607569db65d5": {"relation": "child"}
  }
  …
}
```
In this case the event is related to a task.

For clients which treat UIDs as opaque strings that wouldn't change anything. For other clients it might help to decide where to search for the related object.

Having a proper URI format to identify events and tasks might come in handy in other scenarios when a URI is required (like in certain HTTP headers). It also automatically solves any encoding issues (like when converting iCalendar objects which contain `\` or  `"` in the UID). The challenge is, of course, to convert iCalendar objects with unknown relations.

Anyway, another idea is to keep `relatedTo` as is and only allow relations to objects of the same type. Relations to other object types would be stored as `links`. So a task wouldn't be "related" to an event, it would be "linked" to it. Links also have a media type attribute, so clients can check the type in advance.

Especially if objects of different types are stored in different collections (or like in Android) even in different databases, a link might make much more sense because in a way it's a weaker type of relationship.

**Comment by rsto** [comment]
> Anyway, another idea is to keep relatedTo as is and only allow relations to objects of the same type. Relations to other object types would be stored as links. So a task wouldn't be "related" to an event, it would be "linked" to it. Links also have a media type attribute, so clients can check the type in advance.

Great idea. Let's go with that.

**Comment by rsto** [comment]
In any case, though, clients need to be prepared not get any type information. In case a JSCalendar object is just a translation from iCalendar, the server might have no chance to tell the type of the object (it might not even be stored on the same server).

I don't know of any CalDAV restriction on the RELATED-TO property, have I overlooked any?
